# Naive generation (no draft model)
method: vanilla

llm_path: Qwen/Qwen3-8B

recipe: null

max_length: 4096
cache_implementation: static
warmup_iter: 1
compile_mode: max-autotune

# Target sampling settings (defaults)
do_sample: false
temperature: 0

generator_profiling: true

generator_kwargs:
  prefill_chunk_size: 128
  verify_method: exact
  verify_kwargs: {}
