# beam_engine beam-search draft model (FlashInfer)
method: be_classic_sd_fi

llm_path: meta-llama/Llama-3.1-8B-Instruct
draft_model_path: meta-llama/Llama-3.2-1B-Instruct

recipe: null

max_length: 4096
cache_implementation: static
warmup_iter: 1
# Required for flashinfer to work correctly
compile_mode: max-autotune-no-cudagraphs

# Target sampling settings (defaults)
do_sample: false
temperature: 0

generator_profiling: true

generator_kwargs:
  prefill_chunk_size: 4096
  verify_method: exact
  verify_kwargs: {}

# Draft tree parameters
draft_params:
  temperature: 1.0
  max_depth: 8
  topk_len: 6
