# SubSpec SD (v2) + lossy verification
method: subspec_sd_v2

llm_path: meta-llama/Llama-3.1-8B-Instruct

recipe:
  class_path: specdecodes.helpers.recipes.subspec.hqq_4bit_attn_4bit_mlp_postspec:Recipe

max_length: 4096
cache_implementation: static
warmup_iter: 1
compile_mode: max-autotune

generator_profiling: true

generator_kwargs:
  prefill_chunk_size: 4096
  lossy_verify: true

draft_params:
  temperature: 0.2
  max_depth: 16
  topk_len: 6
  lossy_threshold: 0.3
  lossy_window_size: 6
