# SubSpec SD (v1) example
method: subspec_sd_fi

llm_path: meta-llama/Llama-3.1-8B-Instruct

recipe:
  class_path: specdecodes.helpers.recipes.subspec.hqq_4bit_postspec:Recipe

max_length: 4096
cache_implementation: static
warmup_iter: 1
# Required for flashinfer to work correctly
compile_mode: max-autotune-no-cudagraphs

# Target sampling settings (defaults)
do_sample: false
temperature: 0

generator_profiling: true

generator_kwargs:
  prefill_chunk_size: 256
  verify_method: exact
  verify_kwargs: {}

draft_params:
  temperature: 0.2
  max_depth: 32
  topk_len: 6
