method: classic_sd
vram_limit_gb: 12
seed: 0
device: cuda:0
max_length: 2048

llm_path: Qwen/Qwen2.5-14B-Instruct
draft_model_path: Qwen/Qwen2.5-1.5B-Instruct

do_sample: false
temperature: 0

generator_kwargs:
  prefill_chunk_size: 256
  verify_method: exact
  verify_kwargs: {}

draft_params:
  temperature: 1
  max_depth: 32
  topk_len: 6

recipe:
  class_path: specdecodes.helpers.recipes.offload.layer_offload:LayerOffloadRecipe
  kwargs:
    keep_first_n_layers_on_gpu: 7

cache_implementation: static
warmup_iter: 3
compile_mode: max-autotune
